/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF,meshBounds, useTexture } from "@react-three/drei";
import { useState } from "react";
import { useFrame } from "@react-three/fiber";
import { Color } from "three";

export default function Banana(props) {
    const gato =useTexture("/static/homero.jpg")
    const gato1 =useTexture("/static/john.jpg")
    const bananaRef = useRef(null)
    const [imagen, setImagen] = useState(false)
    const onHandleBanana = (event) => {
        if(imagen){
            bananaRef.current.children[0].children[0].material.map = gato1
        }else{
            bananaRef.current.children[0].children[0].material.map = gato
        }
        
    }
  

    return (
        <group ref={bananaRef} {...props} dispose={null} onClick={onHandleBanana}>
            <mesh receiveShadow={true} scale={15} raycast={meshBounds} onDoubleClick={(e)=>{setImagen(!imagen)}}>
                <mesh>
                    <planeGeometry/>
                    <meshBasicMaterial map={gato}  />
                </mesh>
            </mesh>
        </group>
    );
}

useGLTF.preload("/static/banana.glb");